# 编译环境
language: node_js
# Node 版本
node_js:
  - lts/*
# 安装依赖
install:
  - npm install

# 代码编译
script:
# - export NODE_OPTIONS=--max_old_space_size=4096
  - npm run docs:build # yarn docs:build 部署构建命令
deploy:
  provider: pages
  cleanup: true
  local_dir: docs/.vuepress/dist # 部署的文件夹文件
  github-token: $GITHUB_TOKEN     # travis服务上的token变量
  target-branch: gh-pages # 集成发布到gh-pages上---如果注销掉将不会发布
  keep-history: true
  on:
    branch: feature-1  #这里指的是部署前的源文件分支